rubocop/rubocop-rspec_rails

CHANGELOG.md
docs/antora.yml

- [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.

Release 2.28.0

---

.github/workflows/main.yml
CHANGELOG.md
Gemfile
README.md
docs/modules/ROOT/pages/installation.adoc
rubocop-rspec_rails.gemspec

It is extracted from RuboCop RSpec, but needs to rely on rubocop-rspec_rails from RuboCop RSpec, and RuboCop RSpec Rails also needs to rely on rubocop-rspec. This makes them interdependent, and if you explicitly specify a dependency, you are stuck in an infinite loop.
```
❯ bundle install
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove either gem 'rubocop-rspec' or gem 'rubocop-rspec_rails' and try again.
```
Therefore, this PR changes the dependency to be implicit. The next major version update of RuboCop RSpec will remove the dependency on rubocop-rspec_rails, so we will change the dependency to be explicit at that point.
Before submitting the PR make sure the following …

Implicit dependency on RuboCop RSpec

---

CHANGELOG.md
lib/rubocop-rspec_rails.rb
spec/spec_helper.rb

```
❯ bundle exec rspec
An error occurred while loading spec_helper.
Failure/Error: require 'rubocop-rspec'
NameError:
uninitialized constant RuboCop::Cop::RSpecRails
No examples found.
No examples found.
```

Fix a `NameError` by Cross-Referencing

---

CHANGELOG.md
lib/rubocop/cop/rspec_rails/http_status.rb
lib/rubocop/cop/rspec_rails_cops.rb

Fix: https://github.com/rubocop/rubocop-rspec_rails/issues/9

Fix an error for `RSpecRails/HttpStatus` when no rack gem is loaded with rubocop-rspec

---

CHANGELOG.md
lib/rubocop-rspec_rails.rb

Fix: https://github.com/rubocop/rubocop-rspec_rails/issues/8

Fix an error for unrecognized cop or department `RSpecRails/HttpStatus` when also using rubocop-rails

---

lib/rubocop/cop/rspec_rails/avoid_setup_hook.rb
lib/rubocop/cop/rspec_rails/http_status.rb
lib/rubocop/cop/rspec_rails/minitest_assertions.rb
lib/rubocop/cop/rspec_rails/negation_be_valid.rb
lib/rubocop/cop/rspec_rails/travel_around.rb

Let's depend as little as possible on `::RuboCop::Cop::RSpec::Base` as cop superclass.
Now, only `InferredSpecType` inherits from rubocop-rspec's base class.
See also https://github.com/rubocop/rubocop-rspec/pull/1511

Change superclass for many cops

---

CHANGELOG.md
lib/rubocop-rspec_rails.rb

Fix: https://github.com/rubocop/rubocop-rspec_rails/issues/18
This PR fixes an error for Ambiguous cop name `RSpec/Rails/HttpStatus` in the `rubocop-rspec_rails` gem.

Fix an error for Ambiguous cop name `RSpec/Rails/HttpStatus`

---

.github/workflows/publish.yml

- [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
If you have created a new cop:
If you have modified an existing cop's configuration options:

Fix invalid path and name in publish.yml

---

spec/rubocop/cop/rspec_rails/inferred_spec_type_spec.rb

Fix InternalAffairs/ExampleDescription offenses

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_rspecrails.adoc

Follow up: https://github.com/rubocop/rubocop-rspec/pull/1899
If you have modified an existing cop's configuration options:

Support `AutoCorrect: contextual` option for LSP

---

CHANGELOG.md
config/default.yml
docs/antora.yml
docs/modules/ROOT/pages/cops_rspecrails.adoc
lib/rubocop/rspec_rails/version.rb

Release v2.29.0

---

docs/modules/ROOT/nav.adoc

Antora currently fails with
[11:39:31.695] ERROR (asciidoctor): target of xref not found: cops_rspec_rails.adoc
file: docs/modules/ROOT/nav.adoc
source: https://github.com/rubocop/rubocop-rspec_rails.git (tag: v2.28.0 | start path: docs)
[11:39:31.742] ERROR (asciidoctor): target of xref not found: cops_rspec_rails.adoc
file: docs/modules/ROOT/nav.adoc
source: https://github.com/rubocop/rubocop-rspec_rails.git (tag: v2.29.0 | start path: docs)
[11:39:31.756] ERROR (asciidoctor): target of xref not found: cops_rspec_rails.adoc
file: docs/modules/ROOT/nav.adoc
source: https://github.com/rubocop/rubocop-rspec_rails.git (branch: master | start path: docs)
Notice also how the link to “Cops Documentation → Rails” on https://docs.rubocop.org/rubocop-rspec_rails/index.html does not work. …

Fix documentation xref

---

CHANGELOG.md
lib/rubocop/rspec_rails/version.rb
rubocop-rspec_rails.gemspec

follow up: https://github.com/rubocop/rubocop-rspec/pull/1901
- [-] Squashed related commits together.
- [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.

`AutoCorrect: contextual` needs rubocop v1.61

---

.rubocop.yml
Gemfile
lib/rubocop-rspec_rails.rb
rubocop-rspec_rails.gemspec

The node_pattern file has been removed from rubocop-rspec, and we should no longer require it.
Also, the `RSpec/FilePath` has been split and `RSpec/SpecFilePathFormat` can be configured to work instead.
Fixes #41.

Don't require rubocop/rspec/language/node_pattern

---

CHANGELOG.md
docs/modules/ROOT/pages/cops_rspecrails.adoc
lib/rubocop/cop/rspec_rails/http_status.rb
spec/rubocop/cop/rspec_rails/http_status_spec.rb

Consider the following snippet
```ruby
it { expect(response).to have_http_status("some-string") }
```
`RSpecRails::HttpStatus` (configured with default `symbolic` style) reports this as an offense:
```
C: [Correctable] RSpecRails/HttpStatus: Prefer nil over "some-string" to describe HTTP status code. (https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/HttpStatus)
it { expect(response).to have_http_status("some-string") }
```
Autocorrection looks like `have_http_status(nil)` which leads to runtime error.
I expect the cop to ignore unexpected objects passed as http status code.

Handle unknown HTTP status codes for `RSpecRails::HttpStatus` cop

---

.rubocop.yml
lib/rubocop/rspec_rails/description_extractor.rb

- [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.

Fixes some rubocop offenses

---

.simplecov
lib/rubocop/cop/rspec_rails/http_status.rb
lib/rubocop/cop/rspec_rails/inferred_spec_type.rb
lib/rubocop/cop/rspec_rails/minitest_assertions.rb
lib/rubocop/cop/rspec_rails/negation_be_valid.rb
spec/rubocop/cop/rspec_rails/http_status_spec.rb

In this PR we do two things:
- Instruct SimpleCov to ignore unreachable code. When a `case` or `if` exhausts all branches, but the last `when`/`elsif` documents behavior we don't want to just change it to a fallback `else`. In that case we add a `:noop` or `raise ArgumentError` and use `:nocov:` to tell SimpleCov to ignore it.
- Adds test coverage to spec/rubocop/cop/rspec_rails/http_status_spec.rb for when the rack gem is not loaded.
Those two commits bring line and branch coverage to 100% ✨ 

Improve test coverage

---

CHANGELOG.md
docs/modules/ROOT/pages/cops_rspecrails.adoc
lib/rubocop/cop/rspec_rails/travel_around.rb
spec/rubocop/cop/rspec_rails/travel_around_spec.rb

Fixes: #49
If you have created a new cop:
- [-] Added the new cop to `config/default.yml`.
- [-] The cop is configured as `Enabled: pending` in `config/default.yml`.
- [-] The cop documents examples of good and bad code.
- [-] The tests assert both that bad code is reported and that good code is not reported.
- [-] Set `VersionAdded: "<<next>>"` in `default/config.yml`.
If you have modified an existing cop's configuration options:
- [-] Set `VersionChanged: "<<next>>"` in `config/default.yml`.

Fix a false negative for `RSpecRails/TravelAround` cop when passed as a proc to a travel method

---

tasks/cops_documentation.rake

Follow-up to https://github.com/rubocop/rubocop-rspec/pull/2057.
Replacing the workaround implemention `RuboCop::ConfigLoader.inject_defaults!` with the plugin documentation feature supported by `CopsDocumentationGenerator`.
If you have created a new cop:
If you have modified an existing cop's configuration options:

Use extended `CopsDocumentationGenerator`

---

CHANGELOG.md
docs/antora.yml
lib/rubocop/rspec_rails/version.rb

Let’s publish a plugin’ed version ✨
In the words of @koic:
> AFAIK, this is the last extension gem managed by the RuboCop org that has not yet been released as a plugin. With this release, users will be able to consistently use plugins for all officially maintained gems under the RuboCop org.
>
> Having a consistent usage pattern for gems within the RuboCop org is a meaningful step forward.

Release v2.31.0
